---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggtext)
#library(geofacet)
library(showtext)

showtext_auto()
font_add_google("Nunito", "Nunito")
font <- 'Nunito'
theme_update(
  text = element_text(family = font),
  strip.text = element_text(size = 25, color = 'grey10'),
  plot.caption = element_text(
    size = 20,
    hjust = 1,
    margin = margin(t = 20, b = 10, l = 10),
    color = 'grey30'
  ),
  plot.title = element_text(
    size = 43,
    hjust = 0,
    margin = margin(b = 35, t = 25),
    color = 'grey10'
  ),
  plot.subtitle = element_textbox_simple(
    size = 28,
    hjust = 0,
    margin = margin(b = 40, t = 30, r = 100),
    color = 'grey10'
  ),
  plot.margin = margin(1, 1, 1, 1),
  
  plot.background = element_rect(fill = "#ffffff", color = "#ffffff"),
  panel.spacing = unit(0, "mm"),
  legend.position = 'None',
)

type_colors = c('#ef476f',
                '#800f2f',
                '#f6bd60',
                '#ff9b54')

```


```{r}
blood_type <- tibble::tribble(
               ~`Country/Dependency`, ~`Population[1]`,    ~`O+`,    ~`A+`,    ~`B+`,   ~`AB+`,   ~`O-`,   ~`A-`,   ~`B-`,  ~`AB-`,
                      "Pakistan[47]",        238181034, "30.04%", "21.53%", "30.24%",  "8.83%",  "3.1%", "2.22%", "3.13%", "0.91%",
                        "Russia[54]",        141722205, "29.92%", "31.19%", "17.17%",  "6.72%", "5.28%", "5.51%", "3.03%", "1.18%",
                          "Slovenia",          2102678,  "31.0%",  "33.0%",  "12.0%",   "6.0%",  "7.0%",  "7.0%",  "3.0%",  "1.0%",
                            "Latvia",          1881232,  "30.6%",  "31.0%",  "17.0%",   "6.0%",  "5.4%",  "6.0%",  "3.0%",  "1.0%",
                   "North Macedonia",          2125971,  "30.0%",  "34.0%",  "15.0%",   "6.0%",  "5.0%",  "6.0%",  "3.0%",  "1.0%",
                       "Estonia[22]",          1228624,  "29.5%",  "30.8%",  "20.7%",   "6.3%",  "4.3%",  "4.5%",  "3.0%",  "0.9%",
                           "Croatia",          4227746,  "29.0%",  "36.0%",  "15.0%",   "5.0%",  "5.0%",  "6.0%",  "3.0%",  "1.0%",
                       "Moldova[39]",          3364496,  "28.5%",  "31.8%",  "17.6%",   "7.0%",  "5.0%",  "6.0%",  "3.0%",  "1.1%",
                "Czech Republic[19]",         10702498,  "27.0%",  "36.0%",  "15.0%",   "7.0%",  "5.0%",  "6.0%",  "3.0%",  "1.0%",
                           "Hungary",          9771827,  "27.0%",  "33.0%",  "16.0%",   "8.0%",  "5.0%",  "7.0%",  "3.0%",  "1.0%",
                           "Belarus",          9441842,  "32.3%",  "30.6%",  "15.3%",   "6.8%",  "5.7%",  "5.4%",  "2.7%",  "1.2%",
                      "Slovakia[57]",          5440602,  "27.2%",  "35.7%",  "15.3%",   "6.8%",  "4.8%",  "6.3%",  "2.7%",  "1.2%",
                              "Iraq",         38872655,  "25.5%",  "25.0%",  "32.6%",   "7.4%",  "3.6%",  "2.7%",  "2.7%",  "0.9%",
                        "Albania[2]",          3074579,  "32.1%",  "31.2%",  "14.5%",   "5.2%",  "6.0%",  "5.5%",  "2.6%",  "0.9%",
                              "Iran",         84923314,  "33.5%",  "27.0%",  "22.2%",   "7.0%",  "4.0%",  "3.0%",  "2.5%",  "0.8%",
                            "Serbia",          7012165, "31.92%", "35.28%",  "12.6%",   "4.2%", "6.08%", "6.72%",  "2.4%",  "0.8%",
                        "Azerbaijan",         10205810,  "29.8%",  "30.0%",  "21.1%",   "9.0%",  "3.3%",  "3.4%",  "2.4%",  "1.0%",
                  "Burkina Faso[11]",         21382659, "39.94%", "20.79%", "26.34%",  "5.17%", "3.36%", "1.75%", "2.22%", "0.43%",
                          "Bulgaria",          6966899,  "28.0%",  "37.4%",  "12.8%",   "6.8%",  "5.0%",  "6.6%",  "2.2%",  "1.2%",
                       "Georgia[26]",          4933674,  "34.8%",  "32.3%",  "11.9%",   "6.0%",  "6.2%",  "5.7%",  "2.1%",  "1.0%",
                        "Jordan[34]",         10909567, "33.03%", "32.86%", "16.56%",  "6.28%",  "4.4%", "3.97%", "2.06%", "0.84%",
                       "Ireland[30]",          5176569,  "47.0%",  "26.0%",   "9.0%",   "2.0%",  "8.0%",  "5.0%",  "2.0%",  "1.0%",
              "United Arab Emirates",          9992083,  "44.1%",  "21.9%",  "20.9%",   "4.3%",  "4.3%",  "2.1%",  "2.0%",  "0.4%",
                  "South Africa[59]",         56463617,  "39.0%",  "32.0%",  "12.0%",   "3.0%",  "6.0%",  "5.0%",  "2.0%",  "1.0%",
                      "Australia[6]",         25466459,  "38.0%",  "32.0%",  "12.0%",   "4.0%",  "7.0%",  "6.0%",  "2.0%",  "1.0%",
                   "New Zealand[43]",          4925477,  "38.0%",  "32.0%",   "9.0%",   "3.0%",  "9.0%",  "6.0%",  "2.0%",  "1.0%",
                            "Greece",         10607051,  "37.8%",  "32.2%",  "11.0%",   "4.0%",  "6.6%",  "5.7%",  "2.0%",  "0.7%",
                        "Brazil[10]",        211715973,  "36.0%",  "34.0%",   "8.0%",   "2.5%",  "9.0%",  "8.0%",  "2.0%",  "0.5%",
                         "Lithuania",          2731464,  "36.0%",  "33.0%",  "11.0%",   "4.0%",  "7.0%",  "6.0%",  "2.0%",  "1.0%",
                       "Denmark[20]",          5869410,  "35.0%",  "37.0%",   "8.0%",   "4.0%",  "6.0%",  "7.0%",  "2.0%",  "1.0%",
                       "Germany[27]",         80159662,  "35.0%",  "37.0%",   "9.0%",   "4.0%",  "6.0%",  "6.0%",  "2.0%",  "1.0%",
                     "Luxemburg[36]",           628381,  "35.0%",  "37.0%",   "9.0%",   "4.0%",  "6.0%",  "6.0%",  "2.0%",  "1.0%",
                         "Spain[61]",         50015792,  "35.0%",  "36.0%",   "8.0%",   "2.5%",  "9.0%",  "7.0%",  "2.0%",  "0.5%",
                "United Kingdom[67]",         65761117,  "33.0%",  "30.5%",   "8.0%",   "2.0%", "12.6%", "11.0%",  "2.0%",  "1.0%",
                        "Sweden[62]",         10202491,  "32.0%",  "37.0%",  "10.0%",   "5.0%",  "6.0%",  "7.0%",  "2.0%",  "1.0%",
                           "Ukraine",         43922939,  "32.0%",  "34.0%",  "15.0%",   "5.0%",  "5.0%",  "6.0%",  "2.0%",  "1.0%",
            "Bosnia and Herzegovina",          3835586,  "31.0%",  "36.0%",  "12.0%",   "6.0%",  "5.0%",  "7.0%",  "2.0%",  "1.0%",
                        "Poland[51]",         38282325,  "31.0%",  "32.0%",  "15.0%",   "7.0%",  "6.0%",  "6.0%",  "2.0%",  "1.0%",
                        "Austria[7]",          8859449,  "30.0%",  "37.0%",  "12.0%",   "5.0%",  "6.0%",  "7.0%",  "2.0%", "0.45%",
                       "Finland[23]",          5571665,  "28.0%",  "35.0%",  "16.0%",   "7.0%",  "5.0%",  "6.0%",  "2.0%",  "1.0%",
                         "India[29]",       1339330514,  "28.0%",  "25.8%",  "32.0%",  "14.7%", "2.03%", "1.36%",  "2.0%", "0.48%",
                       "Romania[53]",         21230362,  "28.0%",  "37.0%",  "14.0%",   "7.0%",  "5.0%",  "6.0%",  "2.0%",  "1.0%",
                     "Liechtenstein",            39137,  "34.0%",  "37.0%",  "10.0%",   "4.0%",  "6.0%",  "6.5%",  "1.8%",  "0.7%",
                        "Kazakhstan",         19091949,  "30.7%",  "29.8%",  "24.2%",   "8.3%",  "2.3%",  "2.2%",  "1.8%",  "0.7%",
                           "Lebanon",          5469612,  "38.4%",  "32.3%",   "9.5%",   "3.2%",  "7.7%",  "6.5%",  "1.7%",  "0.7%",
                       "Namibia[41]",          2678191, "50.58%", "20.49%", "20.21%",  "1.02%", "4.22%", "1.71%", "1.69%", "0.08%",
                       "Somalia[58]",         12094640,  "52.8%", "19.36%", "12.32%",  "3.52%",  "7.2%", "2.64%", "1.68%", "0.48%",
                             "Libya",          6890535, "42.64%", "28.86%", "11.19%",   "4.5%", "6.26%", "4.24%", "1.64%", "0.67%",
                       "Tunisia[64]",         11811335, "41.86%", "28.21%", "16.38%",  "4.55%", "4.14%", "2.79%", "1.62%", "0.45%",
                       "Iceland[28]",           350734,  "46.8%",  "27.2%",   "9.0%",   "2.0%",  "8.2%",  "4.8%",  "1.6%",  "0.4%",
                        "Turkey[65]",         82017514,  "29.8%",  "37.8%",  "14.2%",   "7.2%",  "3.9%",  "4.7%",  "1.6%",  "0.8%",
                           "Morocco",         35561654,  "42.3%",  "40.8%",  "14.0%",   "4.0%",  "4.5%",  "3.1%",  "1.5%",  "0.4%",
                             "Italy",         62402659,  "39.0%",  "36.0%",   "7.5%",   "2.5%",  "7.0%",  "6.0%",  "1.5%",  "0.5%",
                 "United States[68]",        334998398,  "37.4%",  "35.7%",   "8.5%",   "3.4%",  "6.6%",  "6.3%",  "1.5%",  "0.6%",
                   "Ivory Coast[31]",         28088455, "47.24%", "20.19%",  "21.7%",  "3.82%", "3.73%", "1.54%", "1.48%",  "0.3%",
                    "Uzbekistan[69]",         30842796, "29.42%", "30.93%", "24.98%",  "9.27%", "1.68%", "1.77%", "1.42%", "0.53%",
                "Dominican Republic",         10499707,  "46.2%",  "26.4%",  "16.9%",   "3.1%",  "3.7%",  "2.1%",  "1.4%",  "0.2%",
                        "Canada[13]",         37694085,  "39.0%",  "36.0%",   "7.6%",   "2.5%",  "7.0%",  "6.0%",  "1.4%",  "0.5%",
                        "France[24]",         67848156,  "36.5%",  "38.2%",   "7.7%",   "2.5%",  "6.5%",  "6.8%",  "1.4%",  "0.4%",
                             "Ghana",         29340248,  "53.8%",  "17.6%",  "18.3%",   "2.8%",  "4.5%",  "1.3%",  "1.3%",  "0.2%",
                   "Netherlands[42]",         17280397,  "39.5%",  "35.0%",   "6.7%",   "2.5%",  "7.5%",  "7.0%",  "1.3%",  "0.5%",
                     "Sri Lanka[60]",         23044123, "43.42%",  "21.0%", "25.78%",  "5.13%", "2.12%", "1.04%", "1.25%", "0.26%",
                        "Norway[46]",          5467439,  "33.2%",  "41.6%",   "6.8%",   "3.4%",  "5.8%",  "7.4%",  "1.2%",  "0.6%",
                             "Yemen",         29884405, "47.84%",  "27.5%", "15.32%",  "2.14%", "3.66%",  "2.1%", "1.17%", "0.16%",
                    "Mauritania[37]",          4005475,  "46.3%", "26.68%", "17.47%",  "3.85%",  "2.8%",  "1.6%",  "1.1%",  "0.2%",
                        "Algeria[3]",         43576691,  "40.0%",  "30.0%",  "15.0%",  "4.25%",  "6.6%",  "2.3%",  "1.1%", "0.75%",
                      "Portugal[52]",         10302674,  "36.2%",  "39.8%",   "6.6%",   "2.9%",  "6.1%",  "6.8%",  "1.1%",  "0.5%",
                       "Nigeria[45]",        219463862, "50.23%", "21.61%", "19.59%",  "3.47%",  "2.7%", "1.16%", "1.05%", "0.19%",
                           "Bahrain",          1505003, "48.48%", "19.35%", "22.61%",  "3.67%", "3.27%", "1.33%", "1.04%", "0.25%",
                  "Saudi Arabia[55]",         34173498,  "47.8%",  "23.9%",  "17.0%",   "4.0%",  "4.0%",  "2.0%",  "1.0%",  "0.3%",
                       "Jamaica[32]",          2808570,  "47.0%",  "23.0%",  "20.0%",   "3.0%",  "3.5%",  "2.0%",  "1.0%",  "0.5%",
                            "Guinea",         12527440, "46.88%", "21.64%", "22.86%",  "4.52%",  "2.0%",  "0.9%",  "1.0%",  "0.2%",
                              "Cuba",         11059062,  "45.8%",  "33.5%",  "10.2%",   "2.9%",  "3.6%",  "2.8%",  "1.0%",  "0.2%",
                             "Syria",         19398448,  "43.0%",  "30.0%",  "14.0%",   "3.7%",  "5.0%",  "3.0%",  "1.0%",  "0.3%",
                          "Ethiopia",        108113150,  "39.0%",  "28.0%",  "21.0%",   "5.0%",  "3.0%",  "2.0%",  "1.0%",  "1.0%",
                         "Mauritius",          1379365,  "38.3%",  "26.0%",  "25.0%",   "6.7%",  "1.7%",  "1.0%",  "1.0%",  "0.3%",
                             "Malta",           457267,  "38.0%",  "41.0%",   "7.0%",   "3.0%",  "5.0%",  "4.5%",  "1.0%",  "0.5%",
                        "Belgium[9]",         11720716,  "36.0%",  "37.0%",   "9.0%",   "3.0%",  "6.0%",  "7.0%",  "1.0%",  "1.0%",
                   "Switzerland[63]",          8403994,  "35.0%",  "38.0%",   "8.0%",   "4.0%",  "6.0%",  "7.0%",  "1.0%",  "1.0%",
                        "Armenia[5]",          3021324,  "29.0%",  "46.3%",  "12.0%",   "5.6%",  "2.0%",  "3.7%",  "1.0%",  "0.4%",
                    "Costa Rica[17]",          5097988,  "49.7%",  "28.5%",  "12.4%",   "3.0%",  "3.4%",  "1.9%",  "0.9%",  "0.2%",
                             "Kenya",         53527936,  "45.6%",  "25.2%", "21.28%",   "4.2%",  "1.8%",  "1.0%",  "0.9%", "0.02%",
                        "Cyprus[18]",          1266676, "35.22%", "40.35%", "11.11%",  "4.72%", "3.85%", "3.48%", "0.87%", "0.40%",
                      "Argentina[4]",         45479118,  "48.9%", "31.54%",   "8.0%",  "2.45%",  "4.9%", "3.16%",  "0.8%", "0.25%",
                             "Sudan",         45561556,  "48.0%",  "27.7%",  "15.2%",   "2.8%",  "3.5%",  "1.8%",  "0.8%",  "0.2%",
                      "Cameroon[12]",         27744989, "46.83%", "24.15%", "21.06%",  "4.29%", "1.79%", "0.92%",  "0.8%", "0.16%",
                   "El Salvador[21]",          6481102,  "62.0%",  "23.0%",  "11.0%",   "1.0%",  "1.0%",  "1.0%",  "0.7%",  "0.3%",
                     "Nicaragua[44]",          6243931,  "62.0%",  "20.0%",  "11.0%",   "4.0%",  "1.0%",  "1.0%",  "0.7%",  "0.3%",
                      "Colombia[16]",         49084841,  "56.3%", "26.11%",  "7.28%",  "1.47%", "5.13%",  "2.7%",  "0.7%", "0.31%",
                          "Honduras",          9235340,  "57.5%",  "27.0%",   "7.8%",   "2.5%",  "2.7%",  "1.7%",  "0.6%",  "0.2%",
                             "Egypt",        104124440,  "45.0%",  "44.0%",   "7.4%",   "4.8%",  "5.0%",  "2.0%",  "0.6%",  "0.2%",
                     "Bangladesh[8]",        164098818, "29.21%",  "26.3%", "33.12%",  "9.59%", "0.53%", "0.48%",  "0.6%", "0.17%",
                           "Bolivia",         11639909, "51.53%", "29.45%", "10.11%",  "1.15%", "4.39%", "2.73%", "0.54%",  "0.1%",
                          "Cambodia",         16926984,  "46.7%",  "27.2%",  "18.5%",   "4.9%",  "1.3%",  "0.8%",  "0.5%",  "0.1%",
                              "Fiji",           935974,  "43.0%",  "33.3%",  "16.5%",   "4.8%",  "1.0%",  "0.7%",  "0.5%",  "0.2%",
                         "Chile[14]",         18186770, "56.62%", "27.16%",  "8.78%",  "1.90%", "3.29%", "1.63%", "0.49%", "0.13%",
                      "Paraguay[48]",          7272639, "56.07%", "28.32%",  "4.72%",  "1.38%", "5.89%", "2.97%", "0.49%", "0.15%",
                         "Gabon[25]",          2284912, "57.55%", "20.52%", "17.19%",  "2.54%", "1.35%", "0.48%", "0.41%", "0.06%",
                        "Uganda[66]",         44712143, "49.29%", "24.11%", "20.29%",  "4.41%", "1.01%", "0.49%", "0.41%", "0.09%",
                          "Zimbabwe",         14546314,  "63.3%",  "18.5%",  "14.6%",  "0.99%",  "1.7%",  "0.5%",  "0.4%", "0.01%",
                        "Mexico[38]",        128649565, "59.09%", "26.23%",  "8.53%",  "1.73%", "2.73%", "1.21%", "0.40%", "0.08%",
                     "Venezuela[70]",         28644603,  "58.3%",  "28.2%",   "5.6%",   "1.9%",  "3.7%",  "1.8%",  "0.4%",  "0.1%",
                  "Papua New Guinea",          7259456,  "48.0%",  "37.2%",   "9.6%",   "2.8%",  "1.0%",  "0.8%",  "0.4%",  "0.2%",
                           "Ecuador",         16904867,  "75.0%",  "14.0%",   "7.1%",   "0.5%", "2.38%",  "0.7%",  "0.3%", "0.02%",
                     "Singapore[56]",          6209660,  "44.7%",  "23.9%",  "24.5%",   "5.6%",  "0.6%",  "0.3%",  "0.3%",  "0.1%",
                           "Myanmar",         56590071,  "35.7%",  "23.8%",  "32.7%",  "6.95%",  "0.3%",  "0.2%",  "0.3%", "0.05%",
                          "Peru[49]",         31914989,  "70.0%",  "18.4%",   "7.8%",   "1.6%",  "1.4%",  "0.5%", "0.28%", "0.02%",
                      "Mongolia[40]",          3198913, "38.45%", "22.89%", "29.93%",  "7.83%", "0.35%", "0.21%", "0.27%", "0.07%",
                       "Congo",        101780263,  "59.5%",  "21.3%",  "15.2%",   "2.4%",  "1.0%",  "0.3%",  "0.2%",  "0.1%",
                           "Vietnam",         98721275,  "41.7%",  "21.9%",  "30.8%",  "4.98%",  "0.3%",  "0.1%",  "0.2%", "0.02%",
                          "Thailand",         68977400,  "40.8%",  "16.9%",  "36.8%",  "4.97%",  "0.2%",  "0.1%",  "0.2%", "0.03%",
                          "Laos[35]",          7574356, "37.52%", "19.73%", "35.36%",  "6.85%",  "0.2%",  "0.1%",  "0.2%", "0.05%",
                             "Nepal",         30327877,  "35.2%",  "36.3%",  "27.1%",   "2.6%",  "0.3%",  "0.2%",  "0.2%",  "0.1%",
                             "Macao",           614458,  "41.5%",  "26.1%",  "25.4%",   "6.3%", "0.33%", "0.17%", "0.15%", "0.05%",
                         "Indonesia",        267026366, "36.82%", "25.87%", "28.85%",  "7.96%", "0.18%", "0.13%", "0.15%", "0.04%",
                         "Hong Kong",          7249907,  "41.5%", "26.13%", "25.34%",  "6.35%", "0.32%", "0.17%", "0.14%", "0.05%",
                          "Malaysia",         32652083, "34.32%", "30.35%", "27.37%",  "7.46%", "0.17%", "0.15%", "0.14%", "0.04%",
                   "Philippines[50]",        109180815,  "45.9%",  "22.9%",  "24.9%",  "5.97%",  "0.1%",  "0.1%",  "0.1%", "0.03%",
                         "Japan[33]",        125507472,  "29.9%",  "39.8%",  "19.9%",   "9.9%", "0.15%",  "0.2%",  "0.1%", "0.05%",
                       "North Korea",         25643466, "27.15%", "31.08%", "30.15%", "11.32%", "0.08%",  "0.1%",  "0.1%", "0.03%",
                         "China[15]",       1397897720,  "35.0%",  "28.0%",  "28.0%",   "8.0%",  "0.1%", "0.08%", "0.09%", "0.03%",
                       "South Korea",         51835110,  "27.9%", "33.87%", "26.92%", "10.98%",  "0.1%", "0.13%", "0.08%", "0.02%",
           "Bhutan[citation needed]",           857423, "38.15%", "29.27%", "23.86%",  "8.41%", "0.06%", "0.04%", "0.04%", "0.01%",
                            "Taiwan",         23603049,  "43.9%",  "25.9%",  "23.9%",   "6.0%", "0.17%",  "0.1%", "0.01%", "0.02%",
                             "World",       7772850805, "37.37%", "27.24%", "22.83%",  "6.22%", "2.69%", "2.09%", "1.16%",  "0.4%"
  )


```

```{r, fig.height=40,fig.width=40}
blood_type_long <- blood_type %>% 
  pivot_longer(cols = `O+`:`AB-`,names_to = 'type',values_to = 'percentage') %>% 
  janitor::clean_names() %>% 
    filter(!country_dependency %in% c('Mauritius','Papua New Guinea','Liechtenstein','Luxemburg')) %>% 
  mutate(percentage = as.numeric(str_remove(percentage,fixed('%'))),
         type = str_remove(type,fixed('+')),
          type = str_remove(type,fixed('-')),

         country_dependency = str_remove(country_dependency,fixed('.')),
         country_dependency = str_remove_all(country_dependency,"\\[.*?\\]")) %>% 
  group_by(country_dependency,type) %>% 
  summarize(percentage = sum(percentage)) %>% 
  ungroup() %>% 
  rename(name = country_dependency) %>% 
  mutate(percentage_sqrd = sqrt(percentage)) %>% 
    mutate(xmax = case_when(type == 'AB'~ -1*percentage_sqrd,
                          type == 'B'~ -1*percentage_sqrd,
                          TRUE ~ percentage_sqrd),
         ymax = case_when(type == 'O'~ -1*percentage_sqrd,
                          type == 'AB'~ -1*percentage_sqrd,
                          TRUE ~ percentage_sqrd)) %>% 
    mutate(text_position = percentage_sqrd/2) %>% 
    mutate(xtext_position = case_when(type == 'AB'~ -1*text_position,
                          type == 'B'~ -1*text_position,
                          TRUE ~ text_position),
         ytext_position = case_when(type == 'O'~ -1*text_position,
                          type == 'AB'~ -1*text_position,
                          TRUE ~ text_position)) %>%
  mutate(name = str_wrap(name,width = 8)) 
  
#paste(round(percentage),'%',sep =''))
countries <- blood_type_long %>% 
  mutate(label = if_else(type == 'AB','',as.character(round(percentage)))) %>% 
  filter(name != 'World') %>% 
  ggplot() +
  geom_rect(aes(xmin = 0,ymin = 0,xmax = xmax,ymax = ymax,
                fill = type )) +
  geom_text(aes(x = xtext_position,y = ytext_position ,label = label),family = font,color = 'grey20',size = 6) +
  scale_fill_manual(values =type_colors ) +
  labs(title = 'Blood Type Distribution by Country',
       subtitle = "Blood type is a classification of blood, based on the presence and absence of particluar antibodies and  antigenic in red blood cells. Blood types are inherited and represent contributions from both parents of an individual. The two most important blood type systems type <i style='color:#ef476f'>A</i>, <i style='color:#f6bd60'>B</i>, <i style='color:#800f2f'>AB</i>, and <i style='color:#ff9b54'>O</i>, with + or - which denotes the RhD status)",
       caption = 'Data: Wikipedia | Visualization: Muhammad Chenariyan Nakhaee @mcnakhaee') +
  coord_fixed() +
  #coord_polar() +
  #facet_geo(~name,grid = world_countries_grid1)
  facet_wrap(vars(name)) 




ggsave("23_Tiles_main.pdf", width = 40, height = 40, device = cairo_pdf)


```
```{r}
type_p <- blood_type_long %>% 
  filter(name == 'World') %>% 
  ggplot() +
  geom_rect(aes(xmin = 0,ymin = 0,xmax = xmax,ymax = ymax,
                fill = type )) +
  geom_text(aes(x = xtext_position,y = ytext_position ,label = type),family = font,color = 'white',size = 12) +
  scale_fill_manual(values = type_colors)+
  coord_fixed() +
  theme(strip.text = element_blank())
ggsave("23_Tiles_legend.pdf", device = cairo_pdf)




```

```{r}
world_p <- blood_type_long %>% 
  filter(name == 'World') %>% 
  ggplot() +
  geom_rect(aes(xmin = 0,ymin = 0,xmax = xmax,ymax = ymax,
                fill = type )) +
  geom_text(aes(x = xtext_position,y = ytext_position ,label = paste(round(percentage),'%',sep ='')),family = font,color = 'white',size = 12) +
  scale_fill_manual(values = type_colors) +
  coord_fixed() +
  #facet_geo(~name,grid = world_countries_grid1)
  facet_wrap(vars(name))

ggsave("23_Tiles_world.pdf", device = cairo_pdf)
```

